language: node_js
node_js:
  - '12'
  - '10'
  - '8'

jobs:
  include:
    - stage: lint
      node_js: '12'
      script: "npm run lint"
    - stage: release
      node_js: '12'
      script: "npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'"
      deploy:
        provider: script
        script: "npm semantic-release"
        on:
          tags: false
stages:
  - lint
  - test
  - name: release
    if: branch = master
